//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_student
    {
        public Admission_student()
        {
            this.DisciplinesSemester = new HashSet<DisciplinesSemester>();
        }
    
        public int Code_adst { get; set; }
        public int Code_dt { get; set; }
        public string AcademicYear_adst { get; set; }
    
        public virtual DirectionTraining DirectionTraining { get; set; }
        public virtual ICollection<DisciplinesSemester> DisciplinesSemester { get; set; }
        public override string ToString() => AcademicYear_adst;
    }
}
