//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectionTraining
    {
        public DirectionTraining()
        {
            this.Admission_student = new HashSet<Admission_student>();
        }
    
        public int Code_dt { get; set; }
        public int Code_levels { get; set; }
        public string Code { get; set; }
        public string Title_dt { get; set; }
    
        public virtual ICollection<Admission_student> Admission_student { get; set; }
        public virtual EducationLevels EducationLevels { get; set; }
        public override string ToString() => Title_dt;
    }
}
