//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplines
    {
        public Disciplines()
        {
            this.DisciplinesSemester = new HashSet<DisciplinesSemester>();
        }
    
        public int Code_discipline { get; set; }
        public string Title_discipline { get; set; }
    
        public virtual ICollection<DisciplinesSemester> DisciplinesSemester { get; set; }
        public override string ToString() => Title_discipline;
    }
}
