//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationLevels
    {
        public EducationLevels()
        {
            this.DirectionTraining = new HashSet<DirectionTraining>();
        }
    
        public int Code_levels { get; set; }
        public string Title_levels { get; set; }
    
        public virtual ICollection<DirectionTraining> DirectionTraining { get; set; }
        public override string ToString() => Title_levels;
    }
}
