//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadRate
    {
        public int Code_lr { get; set; }
        public int Number_hours { get; set; }
        public string AcademicYear_load { get; set; }
        public int Code_position { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
