//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Аккредитационные_показателиEntities : DbContext
    {
        public Аккредитационные_показателиEntities()
            : base("name=Аккредитационные_показателиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicLoad> AcademicLoad { get; set; }
        public DbSet<Admission_student> Admission_student { get; set; }
        public DbSet<As_teacher_pract> As_teacher_pract { get; set; }
        public DbSet<DirectionTraining> DirectionTraining { get; set; }
        public DbSet<Disciplines> Disciplines { get; set; }
        public DbSet<DisciplinesSemester> DisciplinesSemester { get; set; }
        public DbSet<EducationLevels> EducationLevels { get; set; }
        public DbSet<LoadRate> LoadRate { get; set; }
        public DbSet<Management_Master_degree_program> Management_Master_degree_program { get; set; }
        public DbSet<Position> Position { get; set; }
        public DbSet<Practitioners> Practitioners { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
    }
}
