//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.LoadRate = new HashSet<LoadRate>();
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int Code_position { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<LoadRate> LoadRate { get; set; }
        public virtual ICollection<Teacher> Teacher { get; set; }
        public override string ToString() => Title;
    }
}
