//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аккредитационные_показатели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.AcademicLoad = new HashSet<AcademicLoad>();
            this.As_teacher_pract = new HashSet<As_teacher_pract>();
            this.Management_Master_degree_program = new HashSet<Management_Master_degree_program>();
        }
    
        public int Code_teacher { get; set; }
        public string FIO_teacher { get; set; }
        public string TermsAttraction_teacher { get; set; }
        public int Code_position { get; set; }
        public string AcademicDegree_teacher { get; set; }
        public string AcademicTitle_teacher { get; set; }
        public string EducationLevel_teacher { get; set; }
        public string TitleSpecialty_teacher { get; set; }
        public string AssignedQualification_teacher { get; set; }
        public string AdditionalProfEducation_teacher { get; set; }
        public string WorkEducationalActivities_teacher { get; set; }
        public string WorkOtherOrg_teacher { get; set; }
    
        public virtual ICollection<AcademicLoad> AcademicLoad { get; set; }
        public virtual ICollection<As_teacher_pract> As_teacher_pract { get; set; }
        public virtual ICollection<Management_Master_degree_program> Management_Master_degree_program { get; set; }
        public virtual Position Position { get; set; }
        public override string ToString() => FIO_teacher;
    }
}
